/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

/**
 *
 * @author Eliuth Misael
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnIngresoEquipos = new javax.swing.JButton();
        btnIngresoEspacios = new javax.swing.JButton();
        btnIngresoPersonas = new javax.swing.JButton();
        btnPrestamoEquipos = new javax.swing.JButton();
        btnPrestamoEspacios = new javax.swing.JButton();
        btnSalirSistema = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Menú"));
        jPanel2.setForeground(new java.awt.Color(153, 0, 0));

        btnIngresoEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pc.png"))); // NOI18N
        btnIngresoEquipos.setText("Ingreso Equipos");
        btnIngresoEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        btnIngresoEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoEquiposActionPerformed(evt);
            }
        });

        btnIngresoEspacios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lugares.png"))); // NOI18N
        btnIngresoEspacios.setText("Ingreso Espacios");

        btnIngresoPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/personas.png"))); // NOI18N
        btnIngresoPersonas.setText("Ingreso Personas");
        btnIngresoPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoPersonasActionPerformed(evt);
            }
        });

        btnPrestamoEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/prestamoequipo.png"))); // NOI18N
        btnPrestamoEquipos.setText("Ingreso Prestamo de Equipos");

        btnPrestamoEspacios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/briefcase-papers-savings-loans-credit-banking-16.png"))); // NOI18N
        btnPrestamoEspacios.setText("Ingreso Prestamo de espacios");
        btnPrestamoEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamoEspaciosActionPerformed(evt);
            }
        });

        btnSalirSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/eliminar3.png"))); // NOI18N
        btnSalirSistema.setText("Salir");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/loggin2.0.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnIngresoEspacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIngresoPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIngresoEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrestamoEquipos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrestamoEspacios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalirSistema)
                        .addGap(34, 34, 34))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnIngresoEquipos)
                .addGap(18, 18, 18)
                .addComponent(btnIngresoEspacios)
                .addGap(18, 18, 18)
                .addComponent(btnIngresoPersonas)
                .addGap(18, 18, 18)
                .addComponent(btnPrestamoEspacios)
                .addGap(18, 18, 18)
                .addComponent(btnPrestamoEquipos)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnSalirSistema)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.getAccessibleContext().setAccessibleName("Menu");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoEquiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoEquiposActionPerformed

    private void btnIngresoPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresoPersonasActionPerformed

    private void btnPrestamoEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamoEspaciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestamoEspaciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresoEquipos;
    private javax.swing.JButton btnIngresoEspacios;
    private javax.swing.JButton btnIngresoPersonas;
    private javax.swing.JButton btnPrestamoEquipos;
    private javax.swing.JButton btnPrestamoEspacios;
    private javax.swing.JButton btnSalirSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
